spring.application.name=task-manager

# Database connection settings (exemplu pentru PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=postgres
spring.datasource.password=1q2w3e

# Hibernate settings
# 'update': creeaza/actualizeaza schema la pornirea aplicatiei. Perfect pentru dezvoltare!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Specifica dialectul pentru PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect